CREATE OR REPLACE DATABASE WALMART_DB;

CREATE OR REPLACE SCHEMA WALMART_DB.RAW_DATA;

CREATE OR REPLACE SCHEMA WALMART_DB.TRANSFORM_DATA;

CREATE OR REPLACE SCHEMA WALMART_DB.MART_DATA;

USE DATABASE WALMART_DB

USE schema RAW_DATA

-- CREATE STORAGE INTERGRATION BETWEEN SNOWFLAKE AND S3 BUCKET
CREATE OR REPLACE STORAGE INTEGRATION WALMART_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::337964480109:role/walmart_Analysis_EtoE_Project_Role'
STORAGE_ALLOWED_LOCATIONS = ('s3://ivm-walmart-analysis-etoe-project-bucket/data/Walmart_Analysis_Project/')

-- COLLECT THE REQUERED USER ARN AND EXTERNAL ID FROM STORAGE INTEGRATIONC REATED ABOVEW TO CONFIGURE IN AWS S3 TRUST POLICY
DESC INTEGRATION WALMART_S3_INT

--CREATE A FILE FORMAT WHICH WE CANS SPECIFY IN THE EXTERNAL STAGE
CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE;


-- NOW CREATE Create an external stage in Snowflake that points to storage integration created above
CREATE OR REPLACE STAGE WALMART_S3_STAGE
STORAGE_INTEGRATION = WALMART_S3_INT
URL = 's3://ivm-walmart-analysis-etoe-project-bucket/data/Walmart_Analysis_Project/'
FILE_FORMAT = MY_CSV_FORMAT

--VERIFY IF EXTERNAL STAGE IS CREATED CORRECTLY OR NOT
 LIST @WALMART_S3_STAGE 

 SELECT CURRENT_ROLE();


CREATE OR REPLACE EXTERNAL TABLE my_dept_ext_table (
  id INT AS (value:c1::int),
  name STRING AS (value:c2::string),
  entry_date DATE AS (value:c3::date)
)
WITH LOCATION = @WALMART_DB.RAW_DATA.WALMART_S3_STAGE
PATTERN= 'department\.csv'
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1);

CREATE OR REPLACE EXTERNAL TABLE walmart_department (
  -- Example columns: map these to your actual CSV structure
  dept_id INT AS (value:c1::int),
  dept_name STRING AS (value:c2::string)
)
WITH LOCATION = @WALMART_S3_STAGE
PATTERN = 'department\\.csv'
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT);

CREATE OR REPLACE EXTERNAL TABLE walmart_department_ext (
  store_id    INT    AS (value:c1::int),    -- Maps 1st CSV column to an Integer
  dept_id  STRING AS (value:c2::string), -- Maps 2nd CSV column to a String
  date  string AS (value:c3::string),
  weekly_slaes  string AS (value:c4::string),
  Isholiday  string AS (value:c5::string),
  file_name  STRING AS (metadata$filename) -- Optional: tracks which file the data came from
)
WITH LOCATION = @WALMART_S3_STAGE
PATTERN = '.*department\\.csv'
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT);

-- Always refresh after creating or replacing
ALTER EXTERNAL TABLE DEPARTMENT_RAW_DATA REFRESH;

ALTER EXTERNAL TABLE walmart_department_ext REFRESH;

LIST @WALMART_S3_STAGE PATTERN = 'stores\\.csv';
--------------------------------------
--RAW_DATA
select * from WALMART_DB.RAW_DATA.DEPARTMENT_RAW_DATA; --421570
select * from WALMART_DB.RAW_DATA.DEPARTMENT_CLEAN_RAW_DATA; -- 143 distinct dates, 421,570
select * from WALMART_DB.RAW_DATA.STORES_CLEAN_RAW_DATA; -- 45
select *  from WALMART_DB.RAW_DATA.FACT_CLEAN_RAW_DATA; --8190, 182 distinct dates

---------------------------------------
--TRANSFORM_DATA
Select * from WALMART_DB.TRANSFORM_DATA.WALMART_STORE_DIM where store_id = 26 and dept_id = 94 -- 143 distinct dates, 421,570
Select * from WALMART_DB.TRANSFORM_DATA.WALMART_DATE_DIM -- 143 distinct date , 421,570
Select * from WALMART_DB.TRANSFORM_DATA.WALMART_DEPARTMENT_DIM -- 143 distinct date , 421,570

----------------------------------------
--MART_DATA
Select * from WALMART_DB.MART_DATA.WALMART_FACT_TABLE -- 143 distinct dates, 18,970,650
Select * from WALMART_DB.MART_DATA.WALMART_SNAPSHOT 
Select * from WALMART_DB.MART_DATA.WALMART_FACT_VIEW limit 1000
----------------------------------------

-- DROP TABLE IF EXISTS WALMART_DB.RAW_DATA.WALMART_STORE_DIM; 
-- AIRFLOW_DB.SILVER.PATIENTS_TRANSFORM_SPDrop Table WALMART_DB.TRANSFORM_DATA.WALMART_DATE_DIM
-- Drop schema WALMART_DB.TRANSFORM
--DELETE FROM WALMART_DB.MART_DATA.WALMART_SNAPSHOT
--drop table WALMART_DB.TRANSFORM_DATA.WALMART_FACT_TABLE

--------------------------------------------------------------------------------------ANALYSYS REPORTING---------------------------------------------------

 ----------- WEEKLY SALES BYS TORE AND HOLIDAY --------

 SELECT STORE_ID, ISHOLIDAY ,SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES
    FROM WALMART_FACT_VIEW 
    GROUP BY ISHOLIDAY,STORE_ID


------- WEEKLY SALES BY TEMPERATURE AND YEAR --------

SELECT TEMPERATURE, YEAR(TO_DATE(DATE)) FROM WALMART_DB.MART_DATA.WALMART_FACT_VIEW

SELECT 
        TEMPERATURE, -- Assume you have a column or bins for temp
        YEAR(TO_DATE(DATE)) as SALES_YEAR,
        --SUM(WEEKLY_SALES) as TOTAL_SALES
    FROM WALMART_FACT_VIEW
    where SALES_YEAR = 2012
    --GROUP BY 1, 2
    order by TEMPERATURE DESC


    WITH BinnedSales AS (
    SELECT 
        -- 1. Create temperature bins (e.g., bin '20' means 20-29 degrees)
        FLOOR(TEMPERATURE / 10) * 10 AS TEMP_BIN,
        YEAR(TO_DATE(DATE)) AS YEAR_VAL,
        SUM(WEEKLY_SALES) AS TOTAL_SALES
    FROM WALMART_FACT_VIEW
    GROUP BY TEMP_BIN, YEAR_VAL
),
SalesDiff AS (
    SELECT 
        TEMP_BIN,
        YEAR_VAL,
        TOTAL_SALES,
        -- 2. Find the previous bin's sales to calculate the change
        LAG(TOTAL_SALES) OVER (ORDER BY YEAR_VAL, TEMP_BIN) AS PREV_SALES
    FROM BinnedSales
)

SELECT 
    -- 3. Final labels for your X-axis (e.g., "2010 - 20s")
    CONCAT(YEAR_VAL, ' - ', TEMP_BIN, 's') AS LABEL,
    -- The value for the waterfall (first value is absolute, others are relative)
    CASE 
        WHEN PREV_SALES IS NULL THEN TOTAL_SALES 
        ELSE TOTAL_SALES - PREV_SALES 
    END AS SALES_CHANGE,
    -- Measure type for Plotly: 'absolute' for the first bar, 'relative' for changes
    CASE 
        WHEN PREV_SALES IS NULL THEN 'absolute' 
        ELSE 'relative' 
    END AS MEASURE_TYPE
FROM SalesDiff
ORDER BY YEAR_VAL, TEMP_BIN;
    
------- WEEKLY SALES BY STORE SIZE ---------

SELECT  store_size ,SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES
FROM WALMART_FACT_VIEW 
GROUP BY store_size
ORDER BY STORE_SIZE

------ WEEKLY SALES BYS TORE TYPE AND MONTH --------
SELECT  
STORE_TYPE ,
MONTH(TO_DATE(DATE)) AS MONTH,
MONTHNAME(TO_DATE(DATE)) AS MONTHNAME,
SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES
FROM WALMART_FACT_VIEW 
GROUP BY STORE_TYPE, MONTH ,MONTHNAME

------ MARKDOWN SALES BY YEAR AND STORE ----
SELECT
STORE_ID,
YEAR(TO_DATE(DATE)) AS YEAR,
ZEROIFNULL(SUM(TRY_CAST(NULLIF(MARKDOWN1, 'NA') AS FLOAT))) as MARKDOWN1,
ZEROIFNULL(SUM(TRY_CAST(NULLIF(MARKDOWN2, 'NA') AS FLOAT))) as MARKDOWN2,
ZEROIFNULL(SUM(TRY_CAST(NULLIF(MARKDOWN3, 'NA') AS FLOAT))) as MARKDOWN3,
ZEROIFNULL(SUM(TRY_CAST(NULLIF(MARKDOWN4, 'NA') AS FLOAT))) as MARKDOWN4,
ZEROIFNULL(SUM(TRY_CAST(NULLIF(MARKDOWN5, 'NA') AS FLOAT))) as MARKDOWN5
FROM WALMART_FACT_VIEW
GROUP BY STORE_ID, YEAR

------ WEEKLY SALES BY STORE TYPE ----

SELECT  
STORE_TYPE ,
SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES
FROM WALMART_FACT_VIEW 
GROUP BY STORE_TYPE

------- FUEL PRICE BY YEAR -------

SELECT 
SUM(FUEL_PRICE) AS YEARLY_FUEL_PRICE,
YEAR(TO_DATE(DATE)) AS YEAR,
STORE_ID 
FROM WALMART_FACT_VIEW 
GROUP BY YEAR,STORE_ID

---- WEEKLY SALES BY YEAR, MONTH AND DATE -------

--YEAR 
SELECT  
YEAR(TO_DATE(DATE)) AS YEAR,
SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES
FROM WALMART_FACT_VIEW 
GROUP BY YEAR

--MONTH 
SELECT  
MONTHNAME(TO_DATE(DATE)) AS MONTH,
SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES
FROM WALMART_FACT_VIEW 
GROUP BY MONTH

--DATE
SELECT  
DAY(TO_DATE(DATE)) AS DAY,
SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES
FROM WALMART_FACT_VIEW 
GROUP BY DAY
order by DAY

---- WEEKLY SALES BY CPI -------

SELECT 
CPI,
SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES
FROM WALMART_FACT_VIEW 
GROUP BY CPI

---- DEPARTMENT WISE WEEKLY SALES  -------
SELECT 
DEPT_ID,
SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES
FROM WALMART_FACT_VIEW 
GROUP BY DEPT_ID
ORDER BY TOTAL_WEEKLY_SALES DESC

--TOP 5 DEPARTMENT SALES
SELECT 
DEPT_ID,
SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES
FROM WALMART_FACT_VIEW 
GROUP BY DEPT_ID
ORDER BY TOTAL_WEEKLY_SALES DESC
LIMIT 5

